In [1]:
l=[1,2,3]
n=[3,4,5]

In [2]:
l+n

[1, 2, 3, 3, 4, 5]

In [4]:
l*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
n*3

[3, 4, 5, 3, 4, 5, 3, 4, 5]

In [6]:
l+l

[1, 2, 3, 1, 2, 3]

In [7]:
n+n

[3, 4, 5, 3, 4, 5]

In [8]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,-1)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y=np.where(x%2==0,-3,x)
print(y)

[ 1 -3  3 -3  5 -3  7 -3  9 -3 11 -3]


In [10]:
import numpy as np
d=np.array([10,20,30,40,50,60,70,80])
print(d[-4:])

[50 60 70 80]


In [12]:
print(d.itemsize)

4


In [13]:
import numpy as np
a=np.arange(10,50,3)
print(a)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]
